name: Your New Jekyll Site
markdown: redcarpet
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
path:  ''
permalink: /:year/:title/

collections:
  projects:
    output: true
    permalink: /projects/:path/

navigation:
- root: Home
  url: /
- root: About Us
  url: /about
  first-level:
    - text: About Us
      url: /about
    - text: Staff
      url: /about/staff
    - text: Board
      url: /about/board
    - text: SPORE/MSSU
      url: /about/spore-mssu
    - text: Partners Collaborators
      url: /about/partners-collaborators
    - text: Job Postings
      url: /about/jobs
- root: Projects
  url: /projects
- root: Publications
  url: /publications
- root: Contact Us
  url: /contact