---
new_page_extension: md
auto_deploy: false
admin_path: "/admin/"
webhook_url: 
collections:
  _posts:
    label: Posts
  _projects:
    label: Projects
    templates:
    - projects
  _jobs:
    label: Jobs
    templates:
    - jobs
  _people:
    label: People
    templates:
    - people
  _publications:
    label: Publications
  '':
    label: Other Pages
    templates:
    - blahblah
upload_dir: assets/images
public_path: "/assets/images"
front_matter_path: assets/images
use_front_matter_path: true
file_template: ":filename:"
