---
new_page_extension: md
auto_deploy: false
admin_path: "/admin/"
webhook_url: 
collections: 
upload_dir: assets/images
public_path: "/assets/images"
front_matter_path: assets/images
use_front_matter_path: true
file_template: ":filename:"
