---
label: Default
hide_body: false
is_partial: false
fields:
- name: sub-title
  default: ''
  label: Sub title
  type: text
  hidden: false
- type: text
  name: layout
  label: Layout
  default: text
pages:
- cbt4cbt-prescription.md
